### ISSUE TITLE
PO Number value is wrapped in double quotes, newlines and square brackets.

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/purchaseorder-plugin-for-nopcommerce#1]
Steps to reproduce the problem: 
Enter a PO Number in the Payment Information checkout step.  On the Confirm Order step and on the Order Details view, the PO Number value appears wrapped in double quotes and square brackets.  It looks even worse on the PDF invoice, as there are newlines between the double quotes and the square brackets.

![ponumber](https://user-images.githubusercontent.com/7990762/38463778-abeb01ee-3ac7-11e8-91e9-dcc987adcb8e.png)

**Comment by RuS984** [comment]
Closed (https://github.com/nopSolutions/purchaseorder-plugin-for-nopcommerce/commit/47e8ba8be0b300dffbd335d42c222e9af3c3b14f)
