### ISSUE TITLE
purchaseorder-plugin-for-nopcommerce has no way to restrict access based on Customer Roles

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/purchaseorder-plugin-for-nopcommerce#2]
There's no way to restrict access based on customer role in the purchase order plugin settings. I find it odd that all the other payment plugins support this vital feature, except this one. What makes it even more odd is that Merchants normally grant the privilege to pay with a purchase order select customers.

**Comment by exileDev** [comment]
already fixed in 4.20
